### ISSUE TITLE
Inspect failure of docs building task on CI

### ISSUE THREAD

**Issue by lovesh** [docknetwork/dock-substrate#48]
While building docs for PR https://github.com/docknetwork/dock-substrate/pull/47, the CI failed.
Here is the CI run https://github.com/docknetwork/dock-substrate/pull/47/checks?check_run_id=710341352

**Comment by bddap** [comment]
This issue was a result of a breaking change in nightly rustc, and it wasn't just docs. Nightly has been updated so this should no longer be an issue.
